name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/k8s-gcloud:${GITHUB_REF##*/} .
    - name: Push docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-gcloud:${GITHUB_REF##*/}